version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - NODE_ENV=development
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sce_prac1
      - POSTGRES_PASSWORD=f2nV}1.#n7BK
      - POSTGRES_DB=ecommerce
    restart: unless-stopped

volumes:
  postgres_data:
